version: '3'

services:
  database:
    image: 'postgres:latest'
    command: postgres -c 'max_connections=200'
    volumes:
      - ./.database/:/var/lib/postgresql/data/
    ports:
      - 5432:5432
    env_file:
      - .env
    healthcheck:
      test: pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}
      interval: 10s
      timeout: 5s
      retries: 3

  app:
    image: captainziboo/lapelle:latest
    command: pnpm run deploy
    env_file:
      - .env
    depends_on:
      database:
        condition: service_healthy
    